### ISSUE TITLE
Link to knowledge centre docs when published

### ISSUE THREAD

**Issue by sophiegreen** [IBM/cics-bundle-maven#110]
The prerequisites in the readme should point to the knowledge centre for how to set up the CICS bundle deployment API when these are published.

**Comment by vera-chan** [comment]
@sophiegreen Hi Sophie, the Configuring task in KC is at: https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.6.0/configuring/cmci/config-bundle-api.html
Thanks.

**Comment by davenice** [comment]
For now I've linked to https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.6.0/fundamentals/cpsm/cics-bundle-api.html because it made most sense to me! Happy to discuss :)
