### ISSUE TITLE
If a bundle is DISABLED but one of its bundle parts is ENABLED the DISCARD before deploy fails.

### ISSUE THREAD

**Issue by ledina** [IBM/cics-bundle-maven#131]
I am trying to re-deploy a bundle via the maven plugin. The installed bundle resource has one UNUSABLE and one ENABLED bundle parts and as such the bundle itself is in a DISABLED state. The DISCARD fails as a result.

Need to DISABLE before DISCARD irrelevant of the bundle enable status

**Comment by ind1go** [comment]
Thank you for this. This looks to be a bug in the server-side implementation - I will raise an issue there.

**Comment by ledina** [comment]
Happy for work to be tracked there, so closing this issue.
