### ISSUE TITLE
Improvements to the samples

### ISSUE THREAD

**Issue by ledina** [IBM/cics-bundle-maven#132]
- [x] Update samples so that both options can be deployed simultaneously. Currently the war is named the same in both so cannot both be installed and enabled at the same time.

- [x] Add version number to maven-compiler-plugin to fix warning

- [x] Update the docs in regards to issues with certificates/trust store

- [x] Rename default JVM server in the samples

**Comment by ind1go** [comment]
Third issue dealt with in #142.

**Comment by ledina** [comment]
Fourth issue covered by #143. I will look at adding version to maven-compiler-plugin so we can close this issue

**Comment by ledina** [comment]
First issue was covered by #133
