### ISSUE TITLE
NoClassDefFoundError on mvn clean install for demo-war sample

### ISSUE THREAD

**Issue by jshubash** [IBM/cics-bundle-maven#137]
I'm using jdk 1.8. I get this error when I try to create the cics-bundle for the demo-war sample project. 

Command used: mvn clean install
Error messages:
[WARNING] Error injecting: com.ibm.cics.cbmp.BundleWarMojo
java.lang.NoClassDefFoundError: com/ibm/cics/bundle/parts/BundlePublisher$PublishException
...
Failed to execute goal com.ibm.cics:cics-bundle-maven-plugin:1.0.0:bundle-war (default) on project demo-war-bundle: Execution default of goal com.
ibm.cics:cics-bundle-maven-plugin:1.0.0:bundle-war failed: A required class was missing while executing com.ibm.cics:cics-bundle-maven-plugin:1.0.0:bundle
-war: com/ibm/cics/bundle/parts/BundlePublisher$PublishException

**Comment by jshubash** [comment]
I added dependencies in the plugin section to solve this. Thanks!

**Comment by ind1go** [comment]
Glad to hear you got it fixed! It doesn't sound like you should need to do what you did - can you put an example of what you had to change to get it to work?
