### ISSUE TITLE
Modify behaviour so that failing to provide a JVM server when required generates an error

### ISSUE THREAD

**Issue by davenice** [IBM/cics-bundle-maven#138]
Currently we default defaultjvmserver to MYJVMS. However there's no sensible default JVM server name. If users are bundling a Java app, they need to specify a JVM server name.

We should alter the behaviour so that if a JVM server name isn't provided either via defaultjvmserver or specific JVM servers on every relevant project, the build fails and the user is warned.

The only people this will affect is those who genuinely are happy with the default because they have a JVM server called MYJVMS .... it seems that this group will be vanishingly small!

**Comment by IvanHargreaves** [comment]
Hi Dave,  DFHWLP might be a sensible default. That is the value used in the Liberty JVM server samples and is shipped with CICS in the pre-defined RDO groups. That said, a warning might make it more obvious that the user hasn't consciously set it. Resolution of such a warning might be to help populate the field with a value of DFHWLP rather than offering blank.

**Comment by davenice** [comment]
Thanks Ivan - yes we discussed DFHWLP as a default but decided that really if the user was doing Java they needed to set the value to something sensible.

We couldn't get consensus that a majority of users would use DFHWLP a majority of the time, and because of this, and the simplicity of resolving at build time compared to runtime, we opted for forcing the user to specify.

I don't think there will be a way to automatically populate fields because we don't have a custom editor here. However using DFHWLP in our samples could be a better approach than MYJVMS.

**Comment by davenice** [comment]
Had a further chat with Ivan - we reckon the probability is that a new user would use DFHWLP, customising the name is more advanced.

On that basis we think the ideal is to have an error message that tells them to specify a JVM server (e.g. DFHWLP). If that's hard to do then just updating the default is likely to help a bunch of people who are trying to get started.

**Comment by davenice** [comment]
Also we should update our samples to use DFHWLP and DFHOSGI as better suggestions.

**Comment by ledina** [comment]
The JVM server rename is being tracked under #132
