### ISSUE TITLE
I am a NOVICE at maven.  I'm triying to get the simple-liberty cics microprofile4 to work - I'm lost

### ISSUE THREAD

**Issue by rbarrin2** [IBM/cics-bundle-maven#176]
I downloded manven and can run mvn -v
I downloaded the openliberty,io microprofile4 sample

the next step says run mvn liberty:dev 

???? what do I do woth the microprofile4.zip so that that mvn liberty:dev will work.

**Comment by ind1go** [comment]
This sounds like more of a Liberty or Maven issue, but if you're doing it with a view to installing it into CICS, we can certainly help out.

It's not entirely clear to me which sample you've downloaded, so if you could link to it that would be great. However, if I assume it's [this one](https://github.com/OpenLiberty/sample-getting-started) then once you've downloaded it (unzipping it if you downloaded it as a zip) then you need to run the following, making sure that the current working directory is the same directory as the `pom.xml` file in the root of the downloaded project.

```
mvn liberty:dev
```

What's this doing? It's running Maven, and asking it to run the `liberty:dev` task of the project. That task is set up by the Liberty plugin that the `pom.xml` file specifies. By running the command in the same directory as the `pom.xml` file, Maven defaults to reading that `pom.xml` file as its build file.

When you run that command for the first time, a lot of stuff will be downloaded by Maven - plugins, Liberty, and so on. Eventually, you'll see two important lines:

```
...
CWWKT0016I: Web application available (default_host): http://my-host:9080/
...
CWWKF0011I: The sampleAppServer server is ready to run a smarter planet. The sampleAppServer server started in x.xxx seconds.
...
```

Now you're good to go - open the link to that web app and you'll see the sample website.

**Comment by rbarrin2** [comment]
Yes - trying the sample-getting-started liberty application.   Thank you for your explanation.   I did see something unexpected with the provided integration test(s) and posted an issue in sample-getting-started.
.

**Comment by rbarrin2** [comment]
Thanks again for your help.
