### ISSUE TITLE
Error reading Bundle-SymbolicName from OSGi manifest file when using Maven module cics-bundle

### ISSUE THREAD

**Issue by JAMOGRAD** [IBM/cics-bundle-maven#196]
I have a Maven Java project in the IBM Explorer for z/OS. This Eclipse has the Maven for Eclipse plug-in. I have Maven installed on my laptop.

I can build and package the Maven Java project as a "war" file successfully.

Using the instructions here, I create a new Maven project for the CICS bundle. This requires a "parent" so I select the Maven Java project that I already have. This tells me that the parent project must have a packaging type of "pom" so I come out, change the packaging type and do it again.

I don't know what archetypes are and there are no instructions so I just skip them.

Having done this, and Maven->Update Project, I am told to "register the plugin to the pom.xml of the CICS bundle module". I do that successfully. I am then told to change the packaging type to "cics-bundle" which I do by typing it in as it is not selectable.

Error reading Bundle-SymbolicName from OSGi manifest file (com.ibm.cics:cics-bundle-maven-plugin:1.0.3:build:default-build:compile)

I don't know what this means.

**Comment by davenice** [comment]
Hey James,

Are you able to upload the projects so we can try it? I think that might be easier than a back and forward!

If that's not possible, then I think what is being said here is that the cics-bundle-maven-plugin is trying to build the projects that are declared as its dependencies - one of them I think is an OSGi bundle but it can't read the Bundle-SymbolicName attrribute from the MANIFEST.MF file.

I think you're following these instructions - https://github.com/IBM/cics-bundle-maven#create-a-cics-bundle-in-a-separate-module-using-cics-bundle-maven-plugin - I wonder what dependencies you've set.

**Comment by JAMOGRAD** [comment]
I can share them with you internally. I am indeed following those instructions.  The "Maven Module for the CICS bundle" has no dependencies, but the parent does. @davenice

**Comment by holgerknoche** [comment]
We have a similar problem. We use the maven-bundle-plugin to build our OSGi bundles, and this plugin writes the manifest after the compile phase (it has to, as it analyzes the class files). The OSGi bundles and CICS bundles are part of the same multi-module project.
When running "mvn compile" on such a project, building the CICS bundle fails with the aforementioned error. "mvn install" works fine. When opening the project in Eclipse, it also shows the error, although it disappears after running "mvn install".

**Comment by ind1go** [comment]
It turns out this was a little bit of user error, which we've managed to rectify now.

@holgerknoche thank you for your comment. This looks like it is likely to be a different issue. Please could you [raise a new issue](https://github.com/IBM/cics-bundle-maven/issues/new/choose), with your diagnostics in? Thank you.
