### ISSUE TITLE
Support osgibundle with versionRange

### ISSUE THREAD

**Issue by PhilWakelin** [IBM/cics-bundle-maven#202]
In order to support the CICS bundle PHASEIN function to dynamically update an OSGi bundle, we need the ability to build OSGi bundleparts with the following versionRange style syntax:
```<osgibundle symbolicname="mybundle" version="" versionRange="[1.0.0,2.0.0)" jvmserver="JVMSRV1"/>```

**Comment by ind1go** [comment]
Yes, released in 1.0.4.
