### ISSUE TITLE
Please update the read.me document with build command / mvn commands for newbies

### ISSUE THREAD

**Issue by kiwi1969** [IBM/cics-bundle-maven#203]
This is the first time I was doing this using Maven (as opposed to Z/OS Explorer), and I had the following experience, which may have been avoided if the documentation mentioned the mvn commands needed...

1) My OSGi bundle was initially not found by my bundle project, and instead maven searched nexus repository (which then also failed)
This was actually due to me building OSGI project using 'mvn package' where I actually needed **'mvn install'** 
(otherwise the project is not installed into my local m2 repo, and then is not found)

2) Similarly, when building bundle, I didn't initially see the jar in the resulting bundle in the /target folder using 'mvn compile'. 
The correct command was actually **'mvn package'**

**I am sure this is just a rookie error on my part, but updating the read.me wouldn't hurt**

**Comment by KyeMaloy97** [comment]
I am a newcomer to the team and agree that our readme could use some updates to make the commands easier to follow and maybe some explanation of whats going on so people new to maven understand what the commands are doing. I will work on updating it!
