### ISSUE TITLE
Update CICS bundle maven plugin information

### ISSUE THREAD

**Issue by Sarz97** [IBM/cics-bundle-maven#212]
Can we update this git repo https://github.com/IBM/cics-bundle-maven#deploy-a-cics-bundle-using-cics-bundle-maven-plugin with the information about the credentials in pom.xml and using variables? 

More clarity is needed within the CICS bundle maven plugin section to explain the following:
> A user’s own USERID is used to authenticate them. The USERID defined in the pom.xml is the application developer’s USERID profile_prefix.CMCI.DEPLOYER, which is an EJBROLE-class profile requiring read access to the RACF profile. To protect credentials, do not put them in the pom.xml, as this is published within the artifact. Instead, variables should be referenced in pom.xml. The Maven plug-in parses pom.xml to identify credentials, while the bundle deployment API does not read the pom.xml for credentials, but instead passes them along as the authorization header.

**Comment by Sarz97** [comment]
Can I assign this to you Erik? @cssh-erikcao 
Thank you!

**Comment by davenice** [comment]
Resolved by https://github.com/IBM/cics-bundle-maven/pull/214
