### ISSUE TITLE
Add m2e integration for better experience in Eclipse

### ISSUE THREAD

**Issue by ind1go** [IBM/cics-bundle-maven#4]
To improve the workflow in Eclipse, [m2e features](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html) can be used to auto-build with the Eclipse build cycle, and to show generated resources without a manual refresh.

Tasks:
- [ ] Introduce m2e mapping to validate CICS bundles on incremental builds
- [ ] Use BuildContext to communicate file changes to be refreshed

**Comment by davenice** [comment]
I think this issue can close now.
