### ISSUE TITLE
Provide samples for Maven plugin usage

### ISSUE THREAD

**Issue by davenice** [IBM/cics-bundle-maven#69]
We should provide a couple of sample bundles. We could provide both a 'standalone' bundle that packages a pre-existing WAR project, and a WAR project that is configured to produce a bundle.

We should deliver these as sample projects within cics-bundle-maven/samples and build them automatically as part of our build.

**Comment by davenice** [comment]
Samnple with overriden name for war bundle part

**Comment by sophiegreen** [comment]
Also add a sample for overriding the jvm server so you can have multiple bundle parts with different jvm servers
