### ISSUE TITLE
Support EBA bundlepart type

### ISSUE THREAD

**Issue by ind1go** [IBM/cics-bundle-maven#74]
Add an additional supported bundlepart type for Enterprise Bundle Archives.

**Comment by brad-gorman** [comment]
This would be great for our use case. We're stuck with EBAs and OSGi applications.

**Comment by ind1go** [comment]
EBAs are now supported in the latest snapshot build, which is available from the Sonatype Snapshots repository.

If using a separate bundle module, you just need to define a dependency on an EBA module (as per [this test](https://github.com/IBM/cics-bundle-maven/blob/master/cics-bundle-maven-plugin/src/it/test-reactor-eba/test-bundle/pom.xml#L26-L31))

Alternatively, you can output a CICS bundle as part of an EBA module's build using the [bundle-eba](https://ibm.github.io/cics-bundle-maven/bundle-eba-mojo.html) goal.
